{% set version = "0.0.2" %}

package:
  name: rna_blast_analyze
  version: {{ version }}

source:
  url: https://github.com/cas-bioinf/rna_blast_analyze/archive/v{{ version }}.tar.gz
  sha256: 5aaafb47a2f996afa4d6c5b8f46ce15ec5d3ea05d92842ac51685ea51b7b4dfd

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0
  skip: True # [osx or py2k]

requirements:
  build:
    - python>=3.4, <3.7
    - matplotlib
    - dill
    - numpy
    - Jinja2>=2, <3
    - argcomplete>=1.9, <2
    - pandas>=0.22
    - PyPDF2
    - biopython
    - pip
  run:
    - python>=3.4, <3.7
    - matplotlib
    - dill
    - numpy
    - Jinja2>=2, <3
    - pandas>=0.22
    - PyPDF2
    - biopython
    - argcomplete>=1.9, <2
    - perl
    - viennarna>=2.3
    - blast>=2.2.28, <3
    - clustalo>=1.2, <2
    - muscle>=3.8, <4
    - locarna>=1.9.2, <2
    - t_coffee>=10
    - infernal>=1.1, <2
    - rnastructure>=6.0, <7
    - centroid_rna_package>=0.0.15

test:
  commands:
    - rna_blast_analyze --version | grep "{{ version }}"
    - genomes_from_blast -h | grep "Download sequences from BLAST output"

about:
  home: https://github.com/cas-bioinf/rna_blast_analyze
  license: GPL-V2
  license_file: COPYING
  summary: Pipeline for analyzing BLAST search output for non-coding RNAs (ncRNAs). The BLAST query is assumed to be ncRNA.